---
title: On Graduating Online
---

This Sunday, despite the pandemic and state-wide lock down, we
celebrated.  The University of Illinois at Urbana-Champaign
commemorated this yearly event in a unique way: online via
live stream.  Naturally, this is not what I nor hundreds of other
graduates wanted, but it is how we worked around the constraints of
the times.

One of the biggest travesties of moving online is the inability to
meet with friends who would normally be on campus.  Now we are
thousands of kilometers apart, but share our connection through ether
and wire.

Despite the trying situation, I hope to make the best of it: to relish
the isolation and peace; to take a moment to reflect on who I am and
where I want to go.  Naturally this is a process that should happen
over time but now is as good a time as ever to start living
deliberately.

Personally, I am learning how hard it is to find employment, not only
because of a sunk job market but also my own anxiety of applying.  I
am not sure how to deal with this other than saddle-up[fn:1] and slide
bum-first to where I ought to go.

Nonetheless, I am excited to join the UIUC alumni family and step into
a new stage of my life.  Not sure where to go yet, but hopefully it's
cool and is close the the ocean.

* Footnotes

[fn:1] We all have our own unique ways of /saddling-up/.  Hopefully
they are healthy.
